<div class="x_title">
    <h2><?php echo __('Manage comment') ?></h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <table class="table table-striped">
        <tr>
            <th>User</th>
            <th>Comment</th>
            <th></th>
        </tr>
        <?php foreach ($data as $comment): ?>
            <tr>
                <td><?php echo $comment['user_id'] ?></td>
                <td><?php echo $comment['content'] ?></td>
                <td>
                    <a href="<?php echo getAdminUrl('contact/edit/' . $comment['id']) ?>">Edit</a>&nbsp;|&nbsp;
                    <a href="<?php echo getAdminUrl('contact/delete/' . $comment['id']) ?>"
                       onclick="return confirmDelete();">Remove</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <p><a href="<?php echo getAdminUrl('contact/add') ?>">New contact</a></p>
</div>