<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Admin</title>
        <!-- Bootstrap -->
        <link href="<?php echo getUrl('adminhtml/css/bootstrap.min.css') ?>" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo getUrl('adminhtml/css/font-awesome.min.css') ?>" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo getUrl('adminhtml/css/nprogress.css') ?>" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo getUrl('adminhtml/css/custom.min.css') ?>" rel="stylesheet">
    </head>
    <body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="<?php echo getAdminUrl()?>" class="site_title"><i class="fa fa-paw"></i> <span>Dashboard</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="<?php echo getUrl('adminhtml/images/img.jpg') ?>" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2><?php echo Session::get('username') ?></h2>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <!-- /menu profile quick info -->
                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-folder-open-o"></i> CMS <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <?php getAdminMenu('page', 'Page')?>
                                        <?php getAdminMenu('contact', 'Contact')?>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout" href="<?php echo getAdminUrl('user/logout') ?>">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="<?php echo getUrl('adminhtml/images/img.jpg') ?>" alt=""><?php echo Session::get('username') ?>
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;"> Profile</a></li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="badge bg-red pull-right">50%</span>
                                            <span>Settings</span>
                                        </a>
                                    </li>
                                    <li><a href="javascript:;">Help</a></li>
                                    <li><a href="<?php echo getAdminUrl('user/logout') ?>"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <?php if ($messages = Session::getMessage()) : ?>
                                <div class="container container-main">
                                    <?php if (isset($messages['success'])): ?>
                                        <div class="alert alert-success" role="alert"><?php echo $messages['success'] ?></div>
                                    <?php endif ?>
                                    <?php if (isset($messages['error'])): ?>
                                        <div class="alert alert-danger" role="alert"><?php echo $messages['error'] ?></div>
                                    <?php endif ?>
                                </div>
                            <?php endif; ?>
                            <div class="x_panel">
                                <?php echo $content ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>
    <!-- jQuery -->
    <script src="<?php echo getUrl('adminhtml/js/jquery.min.js') ?>"></script>
    <!-- Bootstrap -->
    <script src="<?php echo getUrl('adminhtml/js/bootstrap.min.js') ?>"></script>
    <!-- FastClick -->
    <script src="<?php echo getUrl('adminhtml/js/fastclick.js') ?>"></script>
    <!-- NProgress -->
    <script src="<?php echo getUrl('adminhtml/js/nprogress.js') ?>"></script>
    <!-- Custom Theme Scripts -->
    <script src="<?php echo getUrl('adminhtml/js/custom.min.js') ?>"></script>
    </body>
</html>