<!DOCTYPE html>
<html lang="<?php echo App::getRouter()->getLanguage() ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo getUrl('images/favicons.png') ?>" />
    <title><?php echo Config::get('site_name') ?></title>
    <link rel="stylesheet" href="<?php echo getUrl('css/bootstrap.min.css') ?>" />
    <link rel="stylesheet" href="<?php echo getUrl('css/style.css') ?>" />
</head>
<body>
    <header>
        <nav class="navbar-inverse">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo getUrl()?>">Home</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <?php getMenu('page', 'Page')?>
                        <?php getMenu('contact', 'Contact')?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <?php if ($username = Session::get('username')): ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    Hello: <?php echo $username ?> <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Change password</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <?php getMenu('user/logout', 'Logout')?>
                                </ul>
                            </li>
                        <?php else: ?>
                            <?php getMenu('user/register', 'Register')?>
                            <?php getMenu('user/login', 'Login')?>
                        <?php endif; ?>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
    </header>

    <?php if ($messages = Session::getMessage()) : ?>
    <div class="container container-main">
        <?php if (isset($messages['success'])): ?>
        <div class="alert alert-success" role="alert"><?php echo $messages['success'] ?></div>
        <?php endif ?>
        <?php if (isset($messages['error'])): ?>
        <div class="alert alert-danger" role="alert"><?php echo $messages['error'] ?></div>
        <?php endif ?>
    </div>
    <?php endif; ?>

    <div class="container container-main">
        <?php echo $content ?>
    </div>
    <script src="<?php echo getUrl('js/jquery-3.1.1.min.js') ?>"></script>
    <script src="<?php echo getUrl('js/bootstrap.min.js') ?>"></script>
</body>
</html>
