<!DOCTYPE html>
<html lang="<?php echo App::getRouter()->getLanguage() ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo getUrl('images/favicons.png') ?>" />
    <title><?php echo Config::get('site_name') ?></title>
    <link rel="stylesheet" href="<?php echo getUrl('css/bootstrap.min.css') ?>" />
    <link rel="stylesheet" href="<?php echo getUrl('css/style.css') ?>" />
</head>
<body>
<header>
</header>

<?php if ($messages = Session::getMessage()) : ?>
    <div class="container container-main">
        <?php if (isset($messages['success'])): ?>
            <div class="alert alert-success" role="alert"><?php echo $messages['success'] ?></div>
        <?php endif ?>
        <?php if (isset($messages['error'])): ?>
            <div class="alert alert-danger" role="alert"><?php echo $messages['error'] ?></div>
        <?php endif ?>
    </div>
<?php endif; ?>

<div class="container container-main">
    <?php echo $content ?>
</div>
<script src="<?php echo getUrl('js/jquery-3.1.1.min.js') ?>"></script>
<script src="<?php echo getUrl('js/bootstrap.min.js') ?>"></script>
</body>
</html>
