<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Login</title>
        <link href="<?php echo getUrl('adminhtml/css/bootstrap.min.css') ?>" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo getUrl('adminhtml/css/custom.min.css') ?>" rel="stylesheet">
    </head>
    <body class="login">
    <?php if ($messages = Session::getMessage()) : ?>
        <div class="container container-main">
            <?php if (isset($messages['success'])): ?>
                <div class="alert alert-success" role="alert"><?php echo $messages['success'] ?></div>
            <?php endif ?>
            <?php if (isset($messages['error'])): ?>
                <div class="alert alert-danger" role="alert"><?php echo $messages['error'] ?></div>
            <?php endif ?>
        </div>
    <?php endif; ?>
    <div>
        <?php echo $content ?>
    </div>
    </body>
</html>