<div class="loginbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info" >
        <div class="panel-heading">
            <div class="panel-title">Forgot password</div>
        </div>
        <div class="panel-body">
            <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
            <form action="<?php echo getUrl('user/forgotpassword') ?>" class="form-horizontal" role="form" method="post">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <input id="login-username" type="text" class="form-control" name="email" value="" placeholder="email">
                </div>
                <div class="form-group">
                    <div class="col-sm-12 controls">
                        <button id="btn-login" type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 control">
                        <div class="hr">
                            Don't have an account!
                            <a href="<?php echo getUrl('user/register') ?>">Sign Up Here</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>