<div class="loginbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info" >
        <div class="panel-heading">
            <div class="panel-title">Sign In</div>
            <a class="signinlink" href="#">Forgot password?</a>
        </div>
        <div class="panel-body">
            <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
            <form action="<?php echo getUrl('user/login') ?>" class="form-horizontal" role="form">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="email">
                </div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                </div>
                <div class="form-group">
                    <div class="col-sm-12 controls">
                        <a id="btn-login" href="#" class="btn btn-success">Login</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 control">
                        <div class="hr">
                            Don't have an account!
                            <a href="<?php echo getUrl('user/register') ?>">Sign Up Here</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>