<div class="loginbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info" >
        <div class="panel-heading">
            <div class="panel-title">Reset password</div>
        </div>
        <div class="panel-body">
            <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
            <form action="" class="form-horizontal" role="form" method="post">
                <div class="form-group">
                    <label for="email" class="col-md-3 control-label">New Password</label>
                    <div class="col-md-9">
                        <input type="password" class="form-control" name="password" id="password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12 controls">
                        <button id="btn-login" type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>