<h1>Add page</h1>
<form action="" method="post" class="page-form" style="width: 500px">
    <div class="form-group">
        <label for="title">Title</label>
        <input name="title" type="text" class="form-control" id="title">
    </div>
    <div class="form-group">
        <label for="alias">Alias</label>
        <input name="alias" type="text" class="form-control" id="alias">
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea name="description" id="description" cols="30" rows="5" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="content" id="content" cols="30" rows="5" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label>Publish</label>
        <input type="checkbox" name="is_active" id="is_active">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>