<h1>Login</h1>
<form action="<?php echo getAdminUrl('user/login') ?>" method="post" class="login-form" style="width: 500px">
    <div class="form-group">
        <label for="username">Username</label>
        <input name="username" type="text" class="form-control" id="username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input name="password" type="text" class="form-control" id="password">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>