<a class="hiddenanchor" id="signup"></a>
<a class="hiddenanchor" id="signin"></a>
<div class="login_wrapper">
    <div class="animate form login_form">
        <section class="login_content">
            <form <?php echo getAdminUrl('user/login') ?> method="post">
                <h1>Login Form</h1>
                <div>
                    <input name="username" type="text" class="form-control" placeholder="Username" required="" />
                </div>
                <div>
                    <input name="password" type="password" class="form-control" placeholder="Password" required="" />
                </div>
                <div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
                <div class="clearfix"></div>
                <div class="separator">
                    <div>
                        <h1><i class="fa fa-paw"></i> Gentelella Alela!</h1>
                        <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>