<h1>Add page</h1>
<form action="" method="post" class="page-form" style="width: 500px">
    <div class="form-group">
        <label for="email">Email</label>
        <input name="email" type="text" class="form-control" id="email">
    </div>
    <div class="form-group">
        <label for="name">Name</label>
        <input name="name" type="text" class="form-control" id="name">
    </div>
    <div class="form-group">
        <label for="message">Message</label>
        <textarea name="message" id="message" cols="30" rows="5" class="form-control"></textarea>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>