<div class="x_title">
    <h2><?php echo __('Manage contact') ?></h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <table class="table table-striped">
        <tr>
            <th>Email</th>
            <th>Name</th>
            <th>Message</th>
            <th></th>
        </tr>
        <?php foreach ($data as $contact): ?>
        <tr>
            <td><?php echo $contact['email'] ?></td>
            <td><?php echo $contact['name'] ?></td>
            <td><?php echo $contact['message'] ?></td>
            <td>
                <a href="<?php echo getAdminUrl('contact/edit/' . $contact['id']) ?>">Edit</a>&nbsp;|&nbsp;
                <a href="<?php echo getAdminUrl('contact/delete/' . $contact['id']) ?>"
                   onclick="return confirmDelete();">Remove</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <p><a href="<?php echo getAdminUrl('contact/add') ?>">New contact</a></p>
</div>